title: Mutyala Siddhartha Koushik
description: Full-Stack Developer | AR/VR Intern | Tech Explorer
theme: minima

author:
  name: Siddhartha Koushik
  email: sidkoushik3@gmail.com

# Navigation links (manually added in your layout via Markdown)
