title: Mutyala Siddhartha Koushik
email: sidkoushik3@gmail.com
description: >- 
  Developer Portfolio | MERN, ML, AR/VR
theme: null  # No default theme
markdown: kramdown


# title: 
# description: Full-Stack Developer | AR/VR Intern | Tech Explorer
# theme: minima

# author:
#   name: Siddhartha Koushik
#   email: 

# # Navigation links (manually added in your layout via Markdown)
